print('programmu izstrādāja: Ņikita Burņevičs')
print('    ****')
print('Laukuma aprēķinsģeometriskām figūrām')
print('    ****')
a = float(input('Ievadiet malas A garumu: '))
print('Malas A garums: ', a)
print('    ****')
b = float(input('Ievadiet malas B garumu :'))
print('Malas B garums: ', b)
print('    ****')
h = float(input('Ievadiet augstumu: '))
print('Augstums: ', h)
print('Laukums trijstūrim: ', a*h/2)
print('Laukums trapecei: ', (a+b)/2*h)
print('Laukums paralelogramam: ', a*h)
print('    ****')  
print('Paldies!')
